### ISSUE TITLE
Error reporting not working

### ISSUE THREAD

**Issue by kjawadDeveloper2** [alan-sdk/alan.dart#28]
When i do a transaction with invalid address. It returns the transaction hash and even though through CLI query i see the error. The transaction signing gateway is not throwing this error.

logs: []
raw_log: 'failed to execute message; message index: 0: ID cookbookLOUD already set:
invalid request'

final result = await _transactionSigningGateway.signTransaction(transaction: unsignedTransaction, walletLookupKey: walletLookupKey).mapError<dynamic>((error) { print(error); throw error; }).flatMap( (signed) => _transactionSigningGateway.broadcastTransaction( walletLookupKey: walletLookupKey, transaction: signed, ), );

**Comment by RiccardoM** [comment]
This is because you are broadcasting a transaction using `BroadcastMode.BROADCAST_MODE_SYNC`. Cosmos currently supports three different [broadcast modes](https://docs.cosmos.network/main/run-node/txs.html#generating-signing-and-broadcasting-transactions): 
- `BROADCAST_MODE_SYNC`, which returns immediately as soon as the transaction is sent to the node, without waiting any checks; 
- `BROADCAST_MODE_ASYNC` which returns after the transaction's basic checks have been performed, so if there are any errors within the transaction format you will get them here; 
- `BROADCAST_MODE_BLOCK` which returns after the transaction has been executed (it will take an entire block to do so, so some seconds), so if there are any execution errors you will get them here. 

If you want to get the error you have seen within your application you need to use either `BROADCAST_MODE_BLOCK` but note that this will take longer for the broadcast to execute since it will have to wait the next block to be committed before you get the error back. 

You can change the broadcasting mode by using: 
```dart
final result = await _transactionSigningGateway.signTransaction(
  transaction: unsignedTransaction, 
  walletLookupKey: walletLookupKey
).mapError((error) { 
  print(error); 
  throw error; 
}).flatMap((signed) => _transactionSigningGateway.broadcastTransaction(
  walletLookupKey: walletLookupKey, 
  transaction: signed, {
  mode: BroadcastMode.BROADCAST_MODE_BLOCK
}));
```

**Comment by faddat** [comment]
thank you immensely for the level of detail here.
